services:

  sx-django:
    container_name: sx-django
    build: .
    restart: always
    ports:
    - 8900:8000
    volumes:
    - ./:/app
    depends_on:
      - sx-db

  sx-db:
    image: postgres:14.3-alpine3.16
    container_name: sx-db
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=magoreal
      - POSTGRES_PASSWORD=ojalaque
    volumes:
      - ./db:/var/lib/postgresql/data
