# Generated by Django 4.2.11 on 2024-06-09 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_siteconfiguration_site_logo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alcance",
        ),
    ]
