# Generated by Django 4.2.11 on 2024-06-09 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sitio",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Codigo Sitio"
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100)),
                (
                    "lat",
                    models.FloatField(
                        blank=True, max_length=11, null=True, verbose_name="Latitud"
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        blank=True, max_length=11, null=True, verbose_name="Longitud"
                    ),
                ),
                ("usuario", models.CharField(max_length=12, verbose_name="usuario")),
            ],
        ),
        migrations.CreateModel(
            name="Galeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=10, unique=True)),
                (
                    "sitio",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galeria.sitio",
                    ),
                ),
            ],
        ),
    ]
