# Generated by Django 4.2.11 on 2024-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0003_comentario_imagen_delete_galeria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagen",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="sitio",
            name="slug",
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
    ]
