# Generated by Django 4.2.11 on 2024-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0004_remove_imagen_descripcion_sitio_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitio",
            name="slug",
        ),
        migrations.AlterField(
            model_name="sitio",
            name="sitio",
            field=models.CharField(
                max_length=10, null=True, unique=True, verbose_name="Codigo Sitio"
            ),
        ),
    ]
