# Generated by Django 4.2.11 on 2024-06-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0006_sitio_slug_alter_sitio_sitio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitio",
            name="slug",
        ),
        migrations.AlterField(
            model_name="sitio",
            name="sitio",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Codigo Sitio"
            ),
        ),
    ]
