# Generated by Django 4.2.11 on 2024-06-09 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("galeria", "0008_sitio_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitio",
            name="usuario",
        ),
        migrations.AddField(
            model_name="sitio",
            name="usuarios",
            field=models.ManyToManyField(
                blank=True, related_name="sitios", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
