# Generated by Django 4.2.11 on 2024-06-10 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0010_remove_sitio_usuarios_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="fecha_carga",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="fecha_carga",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
