# Generated by Django 4.2.11 on 2024-06-10 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0014_alter_comentario_fecha_carga_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comentario",
            name="comentario",
        ),
    ]
