# Generated by Django 4.2.11 on 2024-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0015_remove_comentario_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="comentario",
            field=models.TextField(blank=True, null=True),
        ),
    ]
