# Generated by Django 4.2.11 on 2024-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0016_comentario_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitio",
            name="electrico",
            field=models.IntegerField(default=0, verbose_name="Sistema Electrico"),
        ),
        migrations.AddField(
            model_name="sitio",
            name="grava_geomembrana",
            field=models.IntegerField(default=0, verbose_name="Grava y Geomembrana"),
        ),
        migrations.AddField(
            model_name="sitio",
            name="muro",
            field=models.IntegerField(default=0, verbose_name="Muro Perimetral"),
        ),
        migrations.AddField(
            model_name="sitio",
            name="porton_acceso",
            field=models.IntegerField(default=0, verbose_name="Portón y Acceso"),
        ),
        migrations.AddField(
            model_name="sitio",
            name="spat",
            field=models.IntegerField(
                default=0, verbose_name="Sistema Puesto a Tierra"
            ),
        ),
        migrations.AddField(
            model_name="sitio",
            name="terreno",
            field=models.IntegerField(
                default=0, verbose_name="Nivelación y Preparación Terreno"
            ),
        ),
    ]
