# Generated by Django 4.2.11 on 2024-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0017_sitio_electrico_sitio_grava_geomembrana_sitio_muro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitio",
            name="topografia",
            field=models.IntegerField(default=0, verbose_name="Replanteo y nivelacion"),
        ),
    ]
