# Generated by Django 4.2.11 on 2024-06-10 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("galeria", "0018_sitio_topografia"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitio",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sitios_subidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="topografia",
            field=models.IntegerField(default=0, verbose_name="Replanteo"),
        ),
    ]
